### PR TITLE
Scenic Rides

### PR DESCRIPTION
**Pull request by raminka13**
[Clickup Task](https://app.clickup.com/t/86drrgrh5)

- [x] Please change the url slug too.
- [x] Change the navbar name to Scenic Rides
- [x] Change "recreational flight" to "scenic flight" in the form pages.
- [x] New Copy for subheading: Whether interested in seeing Philly from above, organizing a unique family event, or having a special occasion, allow us to take you up in the sky.
- [x] New copy for body text: 
At Pitcairn Flight Academy, we aim to expose as many folks to the world of flight as possible. If you’re not considering becoming a pilot, perhaps you’d be interested in what it’s like to fly above your home in the greater Philadelphia area. We offer recreational and scenic flights as a means to do so.
Fly over notable landmarks in the area while in one of our CFIs' safe, capable hands. A scenic flight is the perfect gift for the aviation enthusiast in your family. It could be used as a unique business outing. A scenic flight even serves as a great date idea!
Drop us a note and organize your scenic flight from Heritage Field Airport today.
- [x] As I'm working on a Mac the Gemfile.lock added a platform, not sure if in deploy will interfere.

### CODE REVIEW

**Review by timjedrek — CHANGES_REQUESTED** [review]
Please change the route: 
image

instead of http://localhost:3000/scenic-rides/new

it should be: http://localhost:3000/scenic-rides

**Comment by raminka13** [comment]
- [x] Route fixed

**Comment by timjedrek** [comment]
One more change please and we're good to go:

image

**Comment by raminka13** [comment]
- [x] Change all mentions of Recreational Flights to Scenic Rides mostly on mailers and confirmations.
- [ ] Did not change the confirmation route, tried different methods but leave it as before.

**Comment by timjedrek** [comment]
I got the scenic flight confirmation page route to work on my local.. not sure what captcha error you were getting.  There is only a honey pot installed for the form. no captcha.

**Comment by raminka13** [comment]
Awesome Tim. Thanks.

**Pull request merged**
